# Apply this manually - do not store real values in git
# Run: kubectl apply -f secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: powerbi-secret
  namespace: default
type: Opaque
stringData:
  CLIENT_SECRET: "~Hy8Q~-g~8Rwq108VQOIalybLVhtGUkjV~Y6QbFv"
  REDIRECT_URI: "https://dashboard.easypay.mn/api/auth/callback"
